### ISSUE TITLE
Discuss: change all headers to #pragma once?

### ISSUE THREAD

**Issue by frizensami** [CS3203-14/SPA#17]
`#pragma once` vs `#ifndef ....`

Most compilers implement pragma, and ifndef is error prone. The only downside of `#pragma` is a situation where certain files hard link to each other, which is very unlikely.

**Comment by jethrokuan** [comment]
I'd go with `#pragma once` everywhere

**Comment by frizensami** [comment]
Ref for myself: #9

**Comment by frizensami** [comment]
Changed for #9 in 439ddca
