### ISSUE TITLE
Discuss+Bring Up: How should we handle testing of private methods?

### ISSUE THREAD

**Issue by frizensami** [CS3203-14/SPA#21]
There seem to be two lines of thinking when it comes to testing
1. Test **only the visible (public) methods** - "We are only testing for visible behavior"
- Advantage: We can modify module internals while limiting the changes to test cases
- Disadvantage: The public interface may be too coarse-grained. Certain private functions might be complex and require testing of their own if much of the logic is implemented there.

2. Test **more** than just public methods.
- How? 
- `#define private public`
- `friend` classes: but not sure how to do yet with catch
- Any "complex function" should be implemented in its own class while exposing the function as public for testing (i.e. convert the problem back to Option 1)
- ??

**Comment by jethrokuan** [comment]
Honestly, I'd just test the public interfaces, and ensure that valid/invalid inputs for the public interface respond with valid outputs. How things are done underneath (in private methods) aren't that important.

Of course, testing private methods allows us to catch errors earlier, but hopefully using something like lldb/gdb should alleviate these issues. Also if this becomes a problem, I think it's a sign that we're not abstracting sufficiently.

**Comment by shinlos** [comment]
I would second what jethro said about simply testing the public interfaces.

I was actually faced with such a dilemma recently, and decided that if the method is indeed so important that it warrants testing but really does not belong to a class, it would be appropriate to move them to a utils class so that they can still be tested.

**Comment by frizensami** [comment]
Okay, thanks all. Sounds like we'll test public interfaces only, and we'll move large methods / groups of methods to their own classes, publicly exposed. :+1:
