### ISSUE TITLE
Build Component: Front-End Parser for SIMPLE

### ISSUE THREAD

**Issue by frizensami** [CS3203-14/SPA#7]
Structure of the Front-End Parser for SIMPLE (**FEP** until a better name is thought of lol)
(subject to change, this is just a starting point)

**Internal functions**
```haskell
lex: String -> [tokens]
parse: [tokens] -> AST
```

**External API**
```c++
// Takes in a SIMPLE program as a string and builds an internal representation of it
void loadProgram(String);
// Returns the Abstract Syntax Tree representation of the SIMPLE program
AST getAST();
```

**Test Regimen**
Test with SIMPLE source, and test that the AST generated is as expected.
SIMPLE source should only contain **procedures** and **assignments**.

A run of this nature should be deterministic 
```c++
// Where s is a SIMPLE source string, and knownAST is the expected AST representation of s
FEP.loadProgram(s); 
assert(FEP.getAST() == knownAST)
```

**Comment by jethrokuan** [comment]
Closed with #14
